name: Test substitution

on: [push]

jobs:
  build-and-deploy-review-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Substitute variables in manifest files
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'manifest.yml'
      env:
        name: probot-review-app
    - run: cat manifest.yml
